package ru.inforion.lab403.utils.ytbot.youtrack.scheme

data class Issue(
    val attachment: MutableCollection<IssueAttachment>?,
    val comments: MutableCollection<IssueComment>,
    val commentsCount: Long,
    val created: Long,
    val customFields: List<CustomField>,
    val description: String?,
    val draftComment: DraftIssueComment,
    val draftOwner: User,
    val externalIssue: ExternalIssue,
    val fields: List<CustomField>,
    val idReadable: String,
    val isDraft: Boolean,
    val links: List<IssueLink>,
    val numberInProject: Long,
    val parent: IssueLink,
    val project: Project,
    val reporter: User,
    val resolved: Long,
    val subtasks: IssueLink,
    val summary: String,
    val tags: MutableCollection<IssueTag>,
    val updated: Long,
    val updater: User,
    val usesMarkdown: Boolean,
    val visibility: Visibility,
    val voters: IssueVoters,
    val votes: Int,
    val watchers: IssueWatchers,
    val wikifiedDescription: String,
    val id: String
)